<?php

namespace Che\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends EntityRepository
{
    /**
     * Get sorted messages list
     *
     * @return Images[]
     */
    public function getMessages()
    {
        return $this->findBy(array(), array('added' => 'DESC'));
    }

    /**
     * Get count of messages
     *
     * @return int
     */
    public function getMessagesCount()
    {
        $queryBuilder = $this->createQueryBuilder('images');
        $queryBuilder->select('count(images.id)');
        $count = $queryBuilder->getQuery()->getSingleScalarResult();
        return $count;
    }
}
