<?php

namespace Che\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViewsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ViewsRepository extends EntityRepository
{
    public function updateCount()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'UPDATE AppBundle:Views v
            SET v.count = v.count + 1'
        );

        $query->execute();
    }

    public function createCounter()
    {
        $counter = new Views();
        $counter->setCount(1);
        $counter->setId(1);
        $entityManager = $this->getEntityManager();
        $entityManager->persist($counter);
        $entityManager->flush();
    }

    public function getCount()
    {
        /** @var Views $entity */
        $entity = $this->find(1);
        if (!$entity) {
            $this->createCounter();
            return 1;
        }

        return $entity->getCount();
    }
}
